import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto_Mono } from "next/font/google";

import "./globals.css";
import NotificationCard from "./components/Notification";
import { NotificationProvider } from "./context/NotificationContext";
import NavbarServer from "./components/NavbarServer";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NotificationProvider>
        <body
          className={`${robotoMono.variable} antialiased`}
        >
          <NavbarServer />
          <NotificationCard />
          <main className="mt-18 "> {children}</main>
        </body>
      </NotificationProvider>

    </html>
  );
}
