drop trigger if exists "trigger_delete_file_on_storage" on "public"."submission_file";

drop policy "Enable delete for users based on user_id" on "public"."submission_file";

drop policy "Enable insert for authenticated users only" on "public"."submission_file";

drop policy "Enable read access for all users" on "public"."submission_file";

drop policy "Policy with table joins" on "public"."submission_file";

revoke delete on table "public"."submission_file" from "anon";

revoke insert on table "public"."submission_file" from "anon";

revoke references on table "public"."submission_file" from "anon";

revoke select on table "public"."submission_file" from "anon";

revoke trigger on table "public"."submission_file" from "anon";

revoke truncate on table "public"."submission_file" from "anon";

revoke update on table "public"."submission_file" from "anon";

revoke delete on table "public"."submission_file" from "authenticated";

revoke insert on table "public"."submission_file" from "authenticated";

revoke references on table "public"."submission_file" from "authenticated";

revoke select on table "public"."submission_file" from "authenticated";

revoke trigger on table "public"."submission_file" from "authenticated";

revoke truncate on table "public"."submission_file" from "authenticated";

revoke update on table "public"."submission_file" from "authenticated";

revoke delete on table "public"."submission_file" from "service_role";

revoke insert on table "public"."submission_file" from "service_role";

revoke references on table "public"."submission_file" from "service_role";

revoke select on table "public"."submission_file" from "service_role";

revoke trigger on table "public"."submission_file" from "service_role";

revoke truncate on table "public"."submission_file" from "service_role";

revoke update on table "public"."submission_file" from "service_role";

alter table "public"."submission_file" drop constraint "submission_file_group_id_fkey";

alter table "public"."submission_file" drop constraint "submission_file_submission_id_fkey";

alter table "public"."submission_file" drop constraint "submission_file_pkey";

drop index if exists "public"."submission_file_pkey";

drop table "public"."submission_file";


  create table "public"."submission_files" (
    "id" bigint generated by default as identity not null,
    "group_id" uuid,
    "submission_id" uuid,
    "original_file_name" text,
    "mime_type" text,
    "size" bigint,
    "storage_path" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."submission_files" enable row level security;

CREATE UNIQUE INDEX submission_files_pkey ON public.submission_files USING btree (id);

alter table "public"."submission_files" add constraint "submission_files_pkey" PRIMARY KEY using index "submission_files_pkey";

alter table "public"."submission_files" add constraint "submission_files_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."submission_files" validate constraint "submission_files_group_id_fkey";

alter table "public"."submission_files" add constraint "submission_files_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."submission_files" validate constraint "submission_files_submission_id_fkey";

grant delete on table "public"."submission_files" to "anon";

grant insert on table "public"."submission_files" to "anon";

grant references on table "public"."submission_files" to "anon";

grant select on table "public"."submission_files" to "anon";

grant trigger on table "public"."submission_files" to "anon";

grant truncate on table "public"."submission_files" to "anon";

grant update on table "public"."submission_files" to "anon";

grant delete on table "public"."submission_files" to "authenticated";

grant insert on table "public"."submission_files" to "authenticated";

grant references on table "public"."submission_files" to "authenticated";

grant select on table "public"."submission_files" to "authenticated";

grant trigger on table "public"."submission_files" to "authenticated";

grant truncate on table "public"."submission_files" to "authenticated";

grant update on table "public"."submission_files" to "authenticated";

grant delete on table "public"."submission_files" to "postgres";

grant insert on table "public"."submission_files" to "postgres";

grant references on table "public"."submission_files" to "postgres";

grant select on table "public"."submission_files" to "postgres";

grant trigger on table "public"."submission_files" to "postgres";

grant truncate on table "public"."submission_files" to "postgres";

grant update on table "public"."submission_files" to "postgres";

grant delete on table "public"."submission_files" to "service_role";

grant insert on table "public"."submission_files" to "service_role";

grant references on table "public"."submission_files" to "service_role";

grant select on table "public"."submission_files" to "service_role";

grant trigger on table "public"."submission_files" to "service_role";

grant truncate on table "public"."submission_files" to "service_role";

grant update on table "public"."submission_files" to "service_role";


  create policy "allow_authenticated 1mt4rzk_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'attachments'::text));



  create policy "allow_authenticated 1mt4rzk_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'attachments'::text));



  create policy "allow_authenticated 1mt4rzk_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'attachments'::text));



  create policy "allow_authenticated 1mt4rzk_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'attachments'::text));



