alter table "public"."projects" drop constraint "projects_award_id_fkey";


  create table "public"."project_awards" (
    "id" bigint generated by default as identity not null,
    "project_id" uuid,
    "award_id" uuid,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."project_awards" enable row level security;

alter table "public"."projects" drop column "award_id";

alter table "public"."projects" add column "group_challenge_id" uuid;

CREATE UNIQUE INDEX project_awards_pkey ON public.project_awards USING btree (id);

alter table "public"."project_awards" add constraint "project_awards_pkey" PRIMARY KEY using index "project_awards_pkey";

alter table "public"."project_awards" add constraint "project_awards_award_id_fkey" FOREIGN KEY (award_id) REFERENCES public.event_awards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project_awards" validate constraint "project_awards_award_id_fkey";

alter table "public"."project_awards" add constraint "project_awards_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project_awards" validate constraint "project_awards_project_id_fkey";

alter table "public"."projects" add constraint "projects_group_challenge_id_fkey" FOREIGN KEY (group_challenge_id) REFERENCES public.group_challenge(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projects" validate constraint "projects_group_challenge_id_fkey";

alter table "public"."projects" add constraint "projects_award_id_fkey" FOREIGN KEY (group_challenge_id) REFERENCES public.event_awards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."projects" validate constraint "projects_award_id_fkey";

grant delete on table "public"."event_awards" to "postgres";

grant insert on table "public"."event_awards" to "postgres";

grant references on table "public"."event_awards" to "postgres";

grant select on table "public"."event_awards" to "postgres";

grant trigger on table "public"."event_awards" to "postgres";

grant truncate on table "public"."event_awards" to "postgres";

grant update on table "public"."event_awards" to "postgres";

grant delete on table "public"."fun_facts" to "postgres";

grant insert on table "public"."fun_facts" to "postgres";

grant references on table "public"."fun_facts" to "postgres";

grant select on table "public"."fun_facts" to "postgres";

grant trigger on table "public"."fun_facts" to "postgres";

grant truncate on table "public"."fun_facts" to "postgres";

grant update on table "public"."fun_facts" to "postgres";

grant delete on table "public"."project_awards" to "anon";

grant insert on table "public"."project_awards" to "anon";

grant references on table "public"."project_awards" to "anon";

grant select on table "public"."project_awards" to "anon";

grant trigger on table "public"."project_awards" to "anon";

grant truncate on table "public"."project_awards" to "anon";

grant update on table "public"."project_awards" to "anon";

grant delete on table "public"."project_awards" to "authenticated";

grant insert on table "public"."project_awards" to "authenticated";

grant references on table "public"."project_awards" to "authenticated";

grant select on table "public"."project_awards" to "authenticated";

grant trigger on table "public"."project_awards" to "authenticated";

grant truncate on table "public"."project_awards" to "authenticated";

grant update on table "public"."project_awards" to "authenticated";

grant delete on table "public"."project_awards" to "postgres";

grant insert on table "public"."project_awards" to "postgres";

grant references on table "public"."project_awards" to "postgres";

grant select on table "public"."project_awards" to "postgres";

grant trigger on table "public"."project_awards" to "postgres";

grant truncate on table "public"."project_awards" to "postgres";

grant update on table "public"."project_awards" to "postgres";

grant delete on table "public"."project_awards" to "service_role";

grant insert on table "public"."project_awards" to "service_role";

grant references on table "public"."project_awards" to "service_role";

grant select on table "public"."project_awards" to "service_role";

grant trigger on table "public"."project_awards" to "service_role";

grant truncate on table "public"."project_awards" to "service_role";

grant update on table "public"."project_awards" to "service_role";

grant delete on table "public"."project_files" to "postgres";

grant insert on table "public"."project_files" to "postgres";

grant references on table "public"."project_files" to "postgres";

grant select on table "public"."project_files" to "postgres";

grant trigger on table "public"."project_files" to "postgres";

grant truncate on table "public"."project_files" to "postgres";

grant update on table "public"."project_files" to "postgres";

grant delete on table "public"."projects" to "postgres";

grant insert on table "public"."projects" to "postgres";

grant references on table "public"."projects" to "postgres";

grant select on table "public"."projects" to "postgres";

grant trigger on table "public"."projects" to "postgres";

grant truncate on table "public"."projects" to "postgres";

grant update on table "public"."projects" to "postgres";

grant delete on table "public"."submission_feedbacks" to "postgres";

grant insert on table "public"."submission_feedbacks" to "postgres";

grant references on table "public"."submission_feedbacks" to "postgres";

grant select on table "public"."submission_feedbacks" to "postgres";

grant trigger on table "public"."submission_feedbacks" to "postgres";

grant truncate on table "public"."submission_feedbacks" to "postgres";

grant update on table "public"."submission_feedbacks" to "postgres";


